#version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       #driver: overlay
       driver: bridge

volumes:
   mysql-cdc-source:

services:
   mysql-db-source:
      image: mysql:8.0.13
      environment:
          MYSQL_DATABASE: betopia_hrm
          MYSQL_ROOT_PASSWORD: root@123
      ports:
          - 3306:3306
      networks:
          - web-app-net
      volumes:
          - mysql-cdc-source:/var/lib/mysql
          - ./mysql-dump:/docker-entrypoint-initdb.d

   phpmyadmin-source:
     image: phpmyadmin/phpmyadmin
     environment:
       PMA_HOST: mysql-db-source
       PMA_PORT: 3306
       PMA_PMADB: betopia_hrm
       MYSQL_ROOT_PASSWORD: root@123
     ports:
       - 8091:80
     networks:
       - web-app-net
     depends_on:
       - mysql-db-source

   zookeeper:
     image: confluentinc/cp-zookeeper:7.5.1
     ports:
       - 2181:2181
       - 2888:2888
       - 3888:3888
     environment:
       - ALLOW_ANONYMOUS_LOGIN=yes
       - SERVER_ID=1
     networks:
       - web-app-net

   kafka:
     image: debezium/kafka:3.0.0.Final  #kafka:3.4.0 is the last working version with zookeeper.
     ports:
       - 9092:9092
       - 9093:9093
     environment:
       - ZOOKEEPER_CONNECT=zookeeper:2181
       - ALLOW_PLAINTEXT_LISTENER=yes
       #- KAFKA_ENABLE_KRAFT=no #From kafka-v3.3.2 replace ZooKeeper with KRaft consensus protocol.
       #Place Device-Current IP Or EC2-Private-IP
       #To connect from an external machine, change localhost to your host's external IP/hostname,
       #EXTERNAL://localhost:9093, If we need to access the kafka from our host-machine for debug purpose.
       #EXTERNAL://<ec2-private-ip>:9093, In case of aws-ec2 instance, we have to broadcast on the ec2's private ip, other wise can't be listen from other ec2 instance.
       - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
       - KAFKA_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
       - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
       - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
       #
       - BROKER_ID=1
       - OFFSETS_TOPIC_REPLICATION_FACTOR=1
       - JMX_PORT=9991
     depends_on:
       - zookeeper
     networks:
       - web-app-net

   kafka-ui:
     image: provectuslabs/kafka-ui
     ports:
       - 8093:8080
     restart: on-failure
     environment:
       - KAFKA_CLUSTERS_0_NAME=local
       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
       - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
       - KAFKA_CLUSTERS_0_READONLY=false
       - AUTH_TYPE="LOGIN_FORM"
       - SPRING_SECURITY_USER_NAME=admin
       - SPRING_SECURITY_USER_PASSWORD=pass
     depends_on:
       - kafka
     networks:
       - web-app-net

   debezium:
     image: debezium/connect:3.0.0.Final
     links:
       - zookeeper
     environment:
       BOOTSTRAP_SERVERS: kafka:9092
       GROUP_ID: 1
       CONFIG_STORAGE_TOPIC: mysql_connect_configs
       OFFSET_STORAGE_TOPIC: mysql_connect_offsets
       STATUS_STORAGE_TOPIC: mysql_connect_statuses
       KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
       VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
     depends_on:
       - zookeeper
       - kafka
     ports:
       - 8094:8083
     networks:
       - web-app-net
     restart: on-failure

   debezium-ui:
     image: debezium/debezium-ui:latest
     environment:
       KAFKA_CONNECT_URIS: http://debezium:8083
#       KAFKA_CONNECT_URIS: http://192.168.0.101:8094
       #KAFKA_CONNECT_URIS: http://192.168.10.24:8094
     depends_on:
       - debezium
     ports:
       - 8095:8080
     networks:
       - web-app-net
     restart: on-failure

#############

#   schema-registry:
#     image: confluentinc/cp-schema-registry
#     environment:
#       - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
#       - SCHEMA_REGISTRY_HOST_NAME=schema-registry
#       #For Debug Only: Place Device-Current IP:
#       - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8084,http://localhost:8084,http://192.168.221.193:8084
#       #- SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8084,http://localhost:8084,http://192.168.0.18:8084
#       #- SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8084,http://localhost:8084
#     ports:
#       - 8084:8081
#     depends_on:
#       - zookeeper
#       - kafka
#     networks:
#       - web-app-net
#################

##End Of Scripts